New features:
--- --------

<Replace this text with a description of one new machine independent feature.
Replicate a similar block to describe each additional new feature.>

[SUN3]	  <Replace this text with a description of one new SUN3 machine
dependent feature.  Replicate a similar block to describe each additional
new feature.>

[VAX]	  <Replace this text with a description of one new VAX machine
dependent feature.  Replicate a similar block to describe each additional
new feature.>

[PMAX]	  <Replace this text with a description of one new PMAX machine
dependent feature.  Replicate a similar block to describe each additional
new feature.>


Bug fixes:
--- -----

<Replace this text with a description of one machine independent bug fix.
Replicate a similar block to describe each additional bug fix.>


[SUN3]	  <Replace this text with a description of one SUN3 machine dependent
bug fix.  Replicate a similar block to describe each additional bug fix.>

[VAX]	  <Replace this text with a description of one VAX machine dependent
bug fix.  Replicate a similar block to describe each additional bug fix.>

[PMAX]	  <Replace this text with a description of one PMAX machine dependent
bug fix.  Replicate a similar block to describe each additional bug fix.>


Organizational changes:
-------------- -------

<Replace this text with a description of one machine independent organizational
change.  Replicate a similar block to describe each additional change.>


[SUN3]	  <Replace this text with a description of one SUN3 machine dependent
organizational change.  Replicate a similar block to describe each additional
change.>

[VAX]	  <Replace this text with a description of one VAX machine dependent
organizational change.  Replicate a similar block to describe each additional
change.>

[PMAX]	  <Replace this text with a description of one PMAX machine dependent
organizational change.  Replicate a similar block to describe each additional
change.>


Special notes:
------- -----

<Replace this text with any special information of interest for this version.>

******** CUT HERE ******** summary of log messages ******** CUT HERE ********
